# Generated by Django 3.0.5 on 2020-06-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20200611_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gshirts',
            name='Item_name',
            field=models.TextField(),
        ),
    ]
