# Generated by Django 3.0.5 on 2020-06-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='item_pcs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='item_size',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
