# Generated by Django 3.0.5 on 2020-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200613_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.TextField()),
                ('adress', models.TextField()),
                ('shop_email', models.TextField()),
                ('shop_number', models.IntegerField()),
                ('shop_order', models.TextField()),
            ],
        ),
    ]
