# Generated by Django 3.0.5 on 2020-06-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shop_order',
            new_name='ord_name',
        ),
        migrations.AddField(
            model_name='order',
            name='cust_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ord_img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ord_pcs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ord_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ord_size',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
