# Generated by Django 3.0.5 on 2020-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200617_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop_number',
            field=models.BigIntegerField(),
        ),
    ]
