# Generated by Django 3.0.5 on 2020-06-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20200617_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
