# Generated by Django 3.0.5 on 2020-06-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_ord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ord_id',
        ),
    ]
